---

- hosts: group1
  become: yes
  tasks:
   - name: Reconfigure Unattended-Upgardes using shell
     shell: | 
       echo 'APT::Periodic::Update-Package-Lists "1";
       APT::Periodic::Unattended-Upgrade "1";' > /etc/apt/apt.conf.d/20auto-upgrades					
