---

- hosts: all
  become: yes
  tasks:
   - name: Remove "unattended-upgrades" package
     apt:
       name: unattended-upgrades
       state: absent
       autoclean: yes
#       autoremove: yes

   - name: Install "unattended-upgrades" package
     apt:
       name: unattended-upgrades
       state: present
