---

- hosts: group1
  become: yes
  tasks:
   - name: Reconfigure Unattended-Upgardes using shell
     shell: echo -e "APT::Periodic::Update-Package-Lists \"1\";\nAPT::Periodic::Unattended-Upgrade \"1\";\n" > /etc/apt/apt.conf.d/20auto-upgrades