---

- hosts: all
  become: yes
  tasks:
   - name: Reconfigure Unattended-Upgardes using shell
     lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: '^APT::Periodic::Update-Package-Lists "0";'
      line: 'APT::Periodic::Update-Package-Lists "1";'

   - name: Reconfigure Unattended-Upgardes using shell
     lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: '^APT::Periodic::Unattended-Upgrade "0";'
      line: 'APT::Periodic::Unattended-Upgrade "1";'
