---

- hosts: group1
  become: yes
  tasks:
   - name: Remove "unattended-upgrades" package
     apt:
       name: unattended-upgrades
       state: absent

   - name: Install "unattended-upgrades" package
     apt:
       name: unattended-upgrades
       state: present