---
- hosts: all
  tasks:
    - name: reboot | {{ inventory_hostname }} check reboot need
      shell: "[ -f /var/run/reboot-required ]"
      failed_when: False
      register: reboot_required

    - debug: var={{ item }}
      with_items:
        - reboot_required.stdout